- name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_BUSH_0A95C391E }}
    action: "upload"
    ###### Repository/Build Configurations ######
    app_location: "/"        # Root folder where index.html is
    api_location: ""         # No API
    output_location: ""      # Leave blank, no build output
    app_build_command: ""    # Explicitly disable build step
    github_id_token: ${{ steps.idtoken.outputs.result }}
    ###### End of Configurations ######
